name: seguridad_plus
description: '" ".'

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0
  flutter_webrtc: ^0.13.1+hotfix.1
  camera: ^0.10.0+1
  http: ^1.1.0
  permission_handler: ^11.0.0
  connectivity_plus: ^6.0.3
  cloud_firestore: ^5.6.6
  livekit_client: ^2.4.5
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  provider: ^6.0.0
  url_launcher: ^6.1.7
  cloud_functions: ^5.5.1
  livekit_components: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
