// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA66-jZy4XBypNx-uuQ52EThGNfiMujAE',
    appId: '1:1075037963688:android:b105a45a3260aad11d099d',
    messagingSenderId: '1075037963688',
    projectId: 'mapaincidentes',
    storageBucket: 'mapaincidentes.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASaj3lGo9TQtEpBXX7KyksxtzSvBzZSwU',
    appId: '1:1075037963688:web:85b3cd531f8dbb011d099d',
    messagingSenderId: '1075037963688',
    projectId: 'mapaincidentes',
    authDomain: 'mapaincidentes.firebaseapp.com',
    storageBucket: 'mapaincidentes.firebasestorage.app',
    measurementId: 'G-L58BSJBGSD',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASaj3lGo9TQtEpBXX7KyksxtzSvBzZSwU',
    appId: '1:1075037963688:web:f6344cd067ba87e41d099d',
    messagingSenderId: '1075037963688',
    projectId: 'mapaincidentes',
    authDomain: 'mapaincidentes.firebaseapp.com',
    storageBucket: 'mapaincidentes.firebasestorage.app',
    measurementId: 'G-VGQ0S0HH45',
  );

}